//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biomarkt_GmbH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkte
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Marke { get; set; }
        public string Kategorie { get; set; }
        public string Preis { get; set; }
    }
}
